"""PDP-Inhalte je Produkt für die Metafelder im Namespace `apb`.

Quelle der Fakten: die Produktbeschreibungen im Shop (Stand 04.10.2026).
Formate der Listenfelder:
  kennzahlen        "Wert | Beschriftung"
  anwendung         "Schritt | Erklärung"
  technische_daten  "Merkmal | Wert"
  faq               "Frage | Antwort"
  zubehoer          Handles anderer Produkte (werden beim Hochladen zu Produkt-IDs)
"""

SYSTEMS = ["Zander", "Liebig", "Deutsch Normal", "Dadant", "Dadant Blatt", "Langstroth", "Systemunabhängig"]
MONTHS = ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"]

_WACHS_FAQ_LAGER = "Wie lagere ich Mittelwände richtig? | Kühl, trocken und lichtgeschützt, am besten flach liegend in der Originalverpackung. Leicht angelaufene Mittelwände (weißlicher Belag) sind unbedenklich und werden von den Bienen normal ausgebaut."
_WACHS_FAQ_EINLOETEN = "Wie bringe ich die Mittelwand ins Rähmchen? | Das Rähmchen wird gedrahtet, die Mittelwand aufgelegt und der Draht mit einem Trafolöter kurz erwärmt, sodass er sich ins Wachs einschmilzt."
_FUTTER_FAQ_WANN = "Wann wird aufgefüttert? | Üblich ist die Auffütterung nach der letzten Honigernte im Spätsommer, damit die Bienen das Futter vor dem Winter einlagern können. Füttere nie, solange Honigräume aufgesetzt sind."
_GLAS_FAQ_SPUELEN = "Muss ich die Gläser vor dem Abfüllen spülen? | Ja. Wir empfehlen, alle Gläser und Deckel nach Erhalt zu waschen und vollständig trocknen zu lassen, damit dein Honig sauber abgefüllt wird."

PRODUCTS = {
    # ------------------------------------------------------------------ Mittelwände
    "dadant-brutraum-mittelwaende-420-260-mm-1-kg": {
        "vorteile": ["100 % reines Bienenwachs", "Maß 420 × 260 mm", "Zellgröße 5,4 mm", "Kontrollierte Imkerqualität"],
        "beutensysteme": ["Dadant"],
        "claim": "Das Fundament für einen starken Dadant-Brutraum.",
        "einleitung": "Große Brutwaben brauchen eine verlässliche Basis. Diese Mittelwände aus 100 % Bienenwachs sind passend für Dadant-Brutraumrähmchen geschnitten und geben deinem Volk mit 5,4-mm-Zellprägung eine saubere Vorlage für gleichmäßigen Wabenbau.",
        "kennzahlen": ["420 × 260 mm | Mittelwandmaß", "5,4 mm | Zellgröße", "1 kg | Packungsgewicht", "100 % | Bienenwachs"],
        "anwendung": [
            "Rähmchen drahten | Dadant-Brutraumrähmchen waagerecht drahten und den Draht straff spannen.",
            "Mittelwand einlöten | Mittelwand auflegen und den Draht mit dem Trafolöter kurz ins Wachs einschmelzen.",
            "Ins Volk geben | Rähmchen während der Bauzeit in den Brutraum hängen – die Bienen ziehen die Zellen aus.",
        ],
        "einsatzmonate": ["Apr", "Mai", "Jun", "Jul"],
        "einsatz_hinweis": "Ausgebaut wird in der Bauzeit von April bis Juli – einlöten kannst du schon im Winter.",
        "technische_daten": ["Beutensystem | Dadant (Brutraum)", "Maß | 420 × 260 mm", "Zellgröße | 5,4 mm", "Material | 100 % Bienenwachs", "Packungsgewicht | 1 kg", "Herkunft | Kontrollierte Produktion"],
        "lieferumfang": ["1 kg Dadant-Brutraum-Mittelwände 420 × 260 mm"],
        "faq": [
            "Wie viele Mittelwände sind in 1 kg? | Die Stückzahl hängt von der Wandstärke ab, deshalb verkaufen wir nach Gewicht. Maßgeblich sind 1 kg Bienenwachs im Format 420 × 260 mm.",
            _WACHS_FAQ_EINLOETEN,
            _WACHS_FAQ_LAGER,
        ],
        "zubehoer": ["trafoloeter-9v-lange-messspitzen", "futtertasche-dadant-446-285-mm"],
    },
    "dnm-mittelwaende-350-200-mm-1-kg": {
        "vorteile": ["100 % reines Bienenwachs", "Deutsch Normalmaß 350 × 200 mm", "Zellgröße 5,4 mm", "1 kg Packungsgewicht"],
        "beutensysteme": ["Deutsch Normal"],
        "claim": "Maßgenau für Deutsch Normal – direkt aus dem Wachs.",
        "einleitung": "Wer im Deutsch Normalmaß imkert, braucht Mittelwände, die ohne Zuschneiden ins Rähmchen passen. Diese Mittelwände aus 100 % Bienenwachs im Format 350 × 200 mm stammen aus kontrollierter Produktion und tragen die bewährte 5,4-mm-Zellprägung.",
        "kennzahlen": ["350 × 200 mm | Mittelwandmaß", "5,4 mm | Zellgröße", "1 kg | Packungsgewicht", "100 % | Bienenwachs"],
        "anwendung": [
            "Rähmchen vorbereiten | DNM-Rähmchen drahten – zum Beispiel unsere Hoffmann-Rähmchen, die bereits gedrahtet sind.",
            "Einlöten | Mittelwand auf den Draht legen und mit dem Trafolöter einschmelzen.",
            "Einhängen | Das fertige Rähmchen zur Bauzeit ins Volk geben.",
        ],
        "einsatzmonate": ["Apr", "Mai", "Jun", "Jul"],
        "einsatz_hinweis": "Ausgebaut wird in der Bauzeit – vorbereiten kannst du die Rähmchen schon im Winter.",
        "technische_daten": ["Beutensystem | Deutsch Normalmaß", "Maß | 350 × 200 mm", "Zellgröße | 5,4 mm", "Material | 100 % Bienenwachs", "Packungsgewicht | 1 kg", "Herkunft | Kontrollierte Produktion"],
        "lieferumfang": ["1 kg DNM-Mittelwände 350 × 200 mm"],
        "faq": [
            "Passen die Mittelwände in DNM-Rähmchen mit 223 mm Höhe? | Ja, das Format 350 × 200 mm ist für Rähmchen im Deutsch Normalmaß gedacht – zum Beispiel unsere DNM-Hoffmann-Rähmchen 394 × 223 mm.",
            _WACHS_FAQ_EINLOETEN,
            _WACHS_FAQ_LAGER,
        ],
        "zubehoer": ["dnm-raehmchen-hoffmann-223-mm-10-stueck", "trafoloeter-9v-lange-messspitzen", "futtertasche-deutsch-normal-393-220-mm"],
    },
    "zander-mittelwande-395-195-mm": {
        "vorteile": ["100 % reines Bienenwachs", "Zandermaß 395 × 195 mm", "Frei von Pestiziden", "Wachs aus dem Bayerischen Wald"],
        "beutensysteme": ["Zander"],
        "claim": "Bienenwachs aus dem Bayerischen Wald – für deine Zanderbeute.",
        "einleitung": "Diese Mittelwände entstehen aus dem Wachs von Imkern aus dem Bayerischen Wald und sind frei von Pestiziden. Im Zander-Standardmaß 395 × 195 mm passen sie in Rähmchen mit Zander-Abmessungen – wahlweise als 10er-, 20er-Packung oder 2 kg.",
        "kennzahlen": ["395 × 195 mm | Zandermaß", "100 % | Bienenwachs", "Pestizidfrei | Wachsqualität", "3 | Packungsgrößen"],
        "anwendung": [
            "Packungsgröße wählen | 10 oder 20 Stück für einzelne Völker, 2 kg für den größeren Bedarf.",
            "Einlöten | Mittelwand in das gedrahtete Zander-Rähmchen einlöten.",
            "Ausbauen lassen | Rähmchen zur Bauzeit zwischen Brutwaben oder an den Rand des Brutnests hängen.",
        ],
        "einsatzmonate": ["Apr", "Mai", "Jun", "Jul"],
        "einsatz_hinweis": "In der Bauzeit von April bis Juli bauen die Bienen Mittelwände am zuverlässigsten aus.",
        "technische_daten": ["Beutensystem | Zander", "Maß | 395 × 195 mm", "Material | 100 % Bienenwachs", "Wachsqualität | Frei von Pestiziden", "Herkunft | Imker aus dem Bayerischen Wald", "Packungsgrößen | 10 Stück, 20 Stück, 2 kg"],
        "lieferumfang": ["Zander-Mittelwände 395 × 195 mm in der gewählten Packungsgröße"],
        "faq": [
            "Welche Packungsgröße lohnt sich? | Für einzelne Völker reichen 10 oder 20 Stück. Wer mehrere Völker erweitert, fährt mit 2 kg meist günstiger pro Mittelwand.",
            "Woher stammt das Wachs? | Das Wachs kommt von Imkern aus dem Bayerischen Wald und ist frei von Pestiziden.",
            _WACHS_FAQ_LAGER,
        ],
        "zubehoer": ["trafoloeter-9v-lange-messspitzen", "futtertasche-zander-477-220-mm"],
    },
    "zander-halb-und-flachzargen-mittelwande-410-145-mm-20-stuck": {
        "vorteile": ["Zwanzig Mittelwände", "100 % reines Bienenwachs", "Maß 410 × 145 mm", "Frei von Pestiziden"],
        "beutensysteme": ["Zander"],
        "claim": "Flache Waben, volle Honigräume.",
        "einleitung": "Für Zander-Halb- und Flachzargen sind diese Mittelwände im Format 410 × 145 mm geschnitten. Das pestizidfreie Wachs stammt von Imkern aus dem Bayerischen Wald – 20 Stück reichen für zwei komplette Zargen.",
        "kennzahlen": ["410 × 145 mm | Mittelwandmaß", "20 | Mittelwände", "100 % | Bienenwachs", "Pestizidfrei | Wachsqualität"],
        "anwendung": [
            "Maß prüfen | Innenmaß deines Halb- oder Flachzargenrähmchens mit 410 × 145 mm vergleichen.",
            "Einlöten | Mittelwand in das gedrahtete Rähmchen einlöten.",
            "Honigraum aufsetzen | Rähmchen zur Tracht im Honigraum ausbauen lassen.",
        ],
        "einsatzmonate": ["Apr", "Mai", "Jun", "Jul"],
        "einsatz_hinweis": "Ideal zur Frühjahrs- und Sommertracht, wenn Honigräume aufgesetzt werden.",
        "technische_daten": ["Beutensystem | Zander Halb- und Flachzarge", "Maß | 410 × 145 mm", "Inhalt | 20 Stück", "Material | 100 % Bienenwachs", "Wachsqualität | Frei von Pestiziden", "Herkunft | Imker aus dem Bayerischen Wald"],
        "lieferumfang": ["20 × Mittelwand 410 × 145 mm"],
        "faq": [
            "Passen die Mittelwände in meine Rähmchen? | Entscheidend ist das Innenmaß deines Rähmchens. Die Mittelwände messen 410 × 145 mm und sind für Zander-Halb- und Flachzargen gedacht.",
            "Woher stammt das Wachs? | Das Wachs kommt von Imkern aus dem Bayerischen Wald und ist frei von Pestiziden.",
            _WACHS_FAQ_LAGER,
        ],
        "zubehoer": ["trafoloeter-9v-lange-messspitzen", "zander-mittelwande-395-195-mm"],
    },
    # ------------------------------------------------------------------ Rähmchen
    "dnm-raehmchen-hoffmann-223-mm-10-stueck": {
        "vorteile": ["Zehn Hoffmann-Rähmchen", "DNM 394 × 223 mm", "Achtfach geöst und waagerecht gedrahtet", "Aus stabilem Lindenholz"],
        "beutensysteme": ["Deutsch Normal"],
        "claim": "Ausgepackt, Mittelwand rein, fertig.",
        "einleitung": "Zehn Rähmchen im Deutsch Normalmaß aus Lindenholz – achtfach geöst und bereits waagerecht gedrahtet. Die Hoffmann-Seitenteile sorgen für den richtigen Wabenabstand, Abstandshalter brauchst du nicht.",
        "kennzahlen": ["394 × 223 mm | Rähmchenmaß", "10 | Rähmchen", "8-fach | geöst", "Linde | Holzart"],
        "anwendung": [
            "Mittelwand auflegen | DNM-Mittelwand 350 × 200 mm auf den bereits gespannten Draht legen.",
            "Einlöten | Draht mit dem Trafolöter kurz erwärmen, bis er im Wachs sitzt.",
            "Einhängen | Rähmchen Seite an Seite einhängen – die Hoffmann-Seiten halten den Abstand.",
        ],
        "einsatzmonate": ["Apr", "Mai", "Jun", "Jul"],
        "einsatz_hinweis": "Im Winter vorbereiten, in der Bauzeit von April bis Juli ins Volk geben.",
        "technische_daten": ["Beutensystem | Deutsch Normalmaß", "Außenmaß | 394 × 223 mm", "Seitenteile | Hoffmann", "Drahtung | Waagerecht, 8-fach geöst", "Holzstärke | ca. 8–10 mm", "Material | Lindenholz"],
        "lieferumfang": ["10 × DNM-Rähmchen Hoffmann 394 × 223 mm, gedrahtet"],
        "faq": [
            "Brauche ich Abstandshalter? | Nein. Die verbreiterten Hoffmann-Seitenteile geben den Wabenabstand vor.",
            "Welche Mittelwand passt? | Unsere DNM-Mittelwände im Format 350 × 200 mm.",
            "Sind die Rähmchen schon gedrahtet? | Ja, sie sind achtfach geöst und waagerecht gedrahtet – du musst nur noch die Mittelwand einlöten.",
        ],
        "zubehoer": ["dnm-mittelwaende-350-200-mm-1-kg", "trafoloeter-9v-lange-messspitzen"],
    },
    "zander-halbmass-raehmchen-110-mm-hoffmann": {
        "vorteile": ["110 mm für den Honigraum", "Mit Hoffmann-Seitenteilen", "Geöst und fertig gedrahtet", "Stabiler Edelstahldraht"],
        "beutensysteme": ["Zander"],
        "claim": "Leichter ernten im Honigraum.",
        "einleitung": "Volle Honigwaben sind schwer. Mit 110 mm Höhe bleiben diese Zander-Halbmaßrähmchen auch bei Frühtracht gut zu handhaben. Getrocknetes Fichten- oder Lindenholz, Edelstahldraht und Hoffmann-Seitenteile machen sie einsatzbereit – im 20er- oder 30er-Pack.",
        "kennzahlen": ["110 mm | Rähmchenhöhe", "20 / 30 | Stück pro Pack", "Edelstahl | Draht", "Hoffmann | Seitenteile"],
        "anwendung": [
            "Packgröße wählen | 20 oder 30 Stück – je nachdem, wie viele Honigräume du bestücken willst.",
            "Mittelwand einlöten | Passend zugeschnittene Mittelwand auf den Edelstahldraht löten.",
            "Honigraum aufsetzen | Rähmchen in die Flachzarge hängen und zur Tracht aufsetzen.",
        ],
        "einsatzmonate": ["Apr", "Mai", "Jun", "Jul", "Aug"],
        "einsatz_hinweis": "Im Honigraum von der Frühtracht bis zur letzten Sommerernte im Einsatz.",
        "technische_daten": ["Beutensystem | Zander (Halbmaß)", "Höhe | 110 mm", "Seitenteile | Hoffmann", "Drahtung | Geöst, Edelstahldraht", "Material | Getrocknetes Fichten- oder Lindenholz", "Packungsgrößen | 20 oder 30 Stück"],
        "lieferumfang": ["20 oder 30 Zander-Halbmaßrähmchen 110 mm (je nach Auswahl)"],
        "faq": [
            "Warum Halbmaß im Honigraum? | Flache Waben sind voll mit Honig deutlich leichter und lassen sich schneller entnehmen und schleudern.",
            "Aus welchem Holz sind die Rähmchen? | Aus getrocknetem Fichten- oder Lindenholz, glatt verarbeitet.",
            "Brauche ich Abstandshalter? | Nein, die Hoffmann-Seitenteile geben den Abstand vor.",
        ],
        "zubehoer": ["trafoloeter-9v-lange-messspitzen", "twist-off-honigglaser-500-g-12-stuck-inkl-deckel"],
    },
    # ------------------------------------------------------------------ Werkzeug
    "trafoloeter-9v-lange-messspitzen": {
        "vorteile": ["Neun Volt Ausgangsspannung", "Lange, präzise Messspitzen", "Für sauberes Mittelwand-Einlöten", "Transformator und Spitzen inklusive"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Mittelwände einlöten in Sekunden.",
        "einleitung": "Der Trafolöter erwärmt den Rähmchendraht mit 9 V Ausgangsspannung so, dass er sich sauber ins Wachs einschmilzt. Die langen Messspitzen erreichen beide Drahtenden bequem – egal welches Rähmchenmaß du nutzt.",
        "kennzahlen": ["9 V | Ausgangsspannung", "220 V / 50 Hz | Netzanschluss", "WT01-9 | Modell", "Lange | Messspitzen"],
        "anwendung": [
            "Auflegen | Mittelwand mittig auf den gespannten Rähmchendraht legen.",
            "Ansetzen | Beide Messspitzen an die Drahtenden setzen und kurz Strom fließen lassen.",
            "Abkühlen | Spitzen abnehmen, sobald der Draht im Wachs liegt – kurz abkühlen lassen, fertig.",
        ],
        "einsatzmonate": ["Jan", "Feb", "Mär", "Apr"],
        "einsatz_hinweis": "Klassische Winterarbeit: Rähmchen vorbereiten, bevor die Saison startet.",
        "technische_daten": ["Modell | WT01-9", "Eingang | 220 V / 50 Hz", "Ausgang | 9 V", "Stecker | Eurostecker", "Gehäuse | Mit Belüftungsschlitzen", "Einsatz | Einlöten von Mittelwänden"],
        "lieferumfang": ["Transformator mit Anschlusskabel", "Messspitzen"],
        "faq": [
            "Wie lange muss ich den Strom fließen lassen? | Nur kurz – sobald der Draht sichtbar ins Wachs sinkt, Spitzen abnehmen. Zu langes Erhitzen schmilzt den Draht durch die Mittelwand.",
            "Funktioniert der Löter mit jedem Rähmchenmaß? | Ja, er ist unabhängig vom Beutensystem. Die langen Messspitzen erreichen die Drahtenden auch bei großen Rähmchen.",
            "Was ist im Lieferumfang? | Der Transformator mit Anschlusskabel und die Messspitzen.",
        ],
        "zubehoer": ["zander-mittelwande-395-195-mm", "dnm-mittelwaende-350-200-mm-1-kg", "dnm-raehmchen-hoffmann-223-mm-10-stueck"],
    },
    # ------------------------------------------------------------------ Gläser
    "dib-einheitsglaser-500-g-12-stuck-inkl-deckel": {
        "vorteile": ["Zwölf DIB-Gläser mit Deckeln", "500 g Fassungsvermögen", "Höhe 9,3 cm", "Durchmesser 8,4 cm"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Das Glas, das deutschen Honig erkennbar macht.",
        "einleitung": "Das Einheitsglas des Deutschen Imkerbundes ist eines der bekanntesten Honiggläser Deutschlands. Im 12er-Karton bekommst du die 500-g-Gläser direkt mit passenden DIB-Deckeln – bereit zum Abfüllen deiner Ernte.",
        "kennzahlen": ["500 g | Füllmenge", "12 | Gläser mit Deckel", "9,3 cm | Höhe", "8,4 cm | Durchmesser"],
        "anwendung": [
            "Spülen | Gläser und Deckel nach Erhalt waschen und vollständig trocknen lassen.",
            "Abfüllen | Geklärten Honig langsam einfüllen, damit wenig Luft eingeschlossen wird.",
            "Verschließen | DIB-Deckel aufschrauben und Gewährverschluss anbringen.",
        ],
        "einsatzmonate": ["Mai", "Jun", "Jul", "Aug"],
        "einsatz_hinweis": "Abgefüllt wird nach Frühjahrs- und Sommerernte – und natürlich immer dann, wenn Nachschub gebraucht wird.",
        "technische_daten": ["Füllmenge | 500 g", "Höhe | 9,3 cm", "Durchmesser | 8,4 cm", "Verschluss | DIB-Deckel", "Verpackungseinheit | 12er-Karton"],
        "lieferumfang": ["12 × DIB-Einheitsglas 500 g", "12 × passender DIB-Deckel", "Versandkarton"],
        "faq": [
            "Darf jeder das DIB-Glas verwenden? | Das Einheitsglas mit Gewährverschluss ist Mitgliedern der Imkervereine im Deutschen Imkerbund vorbehalten, die ihren Honig nach den D.I.B.-Richtlinien vermarkten. Die Gewährverschlüsse bekommst du über deinen Imkerverein.",
            "Sind die Deckel dabei? | Ja, jedes Glas kommt mit passendem DIB-Deckel.",
            _GLAS_FAQ_SPUELEN,
        ],
        "zubehoer": ["neutrale-honigglaser-500-g-12-stuck-inkl-deckel", "twist-off-honigglaser-500-g-12-stuck-inkl-deckel"],
    },
    "twist-off-honigglaser-500-g-12-stuck-inkl-deckel": {
        "vorteile": ["Zwölf Gläser mit Deckeln", "500 g Fassungsvermögen", "Robustes Rundglas", "Goldfarbener Twist-off-Verschluss"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Goldener Deckel, Bienenmotiv – ein Glas zum Verschenken.",
        "einleitung": "Rundgläser aus robustem Glas mit Bienenmotiv und goldfarbenem Twist-off-Deckel. Ideal für deinen Honig, aber genauso für Marmelade oder selbstgemachte Geschenke – sicher verpackt im 12er-Karton.",
        "kennzahlen": ["500 g | Füllmenge", "12 | Gläser mit Deckel", "Gold | Twist-off-Deckel", "Bienenmotiv | auf jedem Glas"],
        "anwendung": [
            "Spülen | Gläser und Deckel nach Erhalt waschen und trocknen lassen.",
            "Abfüllen | Honig, Marmelade oder Aufstrich einfüllen.",
            "Zudrehen | Twist-off-Deckel aufsetzen und mit einer Vierteldrehung verschließen.",
        ],
        "einsatzmonate": ["Mai", "Jun", "Jul", "Aug"],
        "einsatz_hinweis": "Hochsaison nach der Honigernte – als Geschenkglas aber das ganze Jahr gefragt.",
        "technische_daten": ["Füllmenge | 500 g", "Form | Rundglas mit Bienenmotiv", "Verschluss | Twist-off-Metalldeckel, goldfarben", "Verpackungseinheit | 12er-Karton"],
        "lieferumfang": ["12 × Twist-off-Glas 500 g", "12 × Metalldeckel gold", "Versandkarton"],
        "faq": [
            "Eignen sich die Gläser auch für Marmelade? | Ja, die Gläser sind vielseitig – für Honig, Marmelade, Gewürze und mehr.",
            "Wie werden die Gläser verschickt? | Sicher verpackt im 12er-Karton, um Bruch beim Transport zu vermeiden.",
            _GLAS_FAQ_SPUELEN,
        ],
        "zubehoer": ["neutrale-honigglaser-500-g-12-stuck-inkl-deckel", "dib-einheitsglaser-500-g-12-stuck-inkl-deckel"],
    },
    "neutrale-honigglaser-500-g-12-stuck-inkl-deckel": {
        "vorteile": ["Zwölf neutrale Honiggläser", "Deckel bereits enthalten", "500 g Fassungsvermögen", "Produziert in Deutschland"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Neutral im Glas, stark im Preis.",
        "einleitung": "Das neutrale 500-g-Honigglas lässt deinem eigenen Etikett den Auftritt. Produziert in Deutschland, inklusive Deckel und im 12er-Karton mit der Aufschrift „Bienenhonig – Kraftquelle für den ganzen Tag“.",
        "kennzahlen": ["500 g | Füllmenge", "12 | Gläser mit Deckel", "Deutschland | Produktion", "Neutral | für dein Etikett"],
        "anwendung": [
            "Spülen | Gläser und Deckel nach Erhalt waschen und trocknen lassen.",
            "Abfüllen | Honig einfüllen und Deckel fest verschließen.",
            "Etikettieren | Eigenes Etikett aufbringen – das neutrale Glas lässt dir freie Hand.",
        ],
        "einsatzmonate": ["Mai", "Jun", "Jul", "Aug"],
        "einsatz_hinweis": "Nach der Ernte abfüllen und mit deinem eigenen Etikett vermarkten.",
        "technische_daten": ["Füllmenge | 500 g", "Ausführung | Neutral, ohne Aufdruck", "Verschluss | Deckel inklusive", "Herkunft | Produziert in Deutschland", "Verpackungseinheit | 12er-Karton mit Aufdruck"],
        "lieferumfang": ["12 × neutrales Honigglas 500 g", "12 × Deckel", "Karton „Bienenhonig – Kraftquelle für den ganzen Tag“"],
        "faq": [
            "Kann ich eigene Etiketten verwenden? | Ja, genau dafür ist das neutrale Glas gemacht.",
            "Wo werden die Gläser hergestellt? | Die Gläser werden in Deutschland produziert.",
            _GLAS_FAQ_SPUELEN,
        ],
        "zubehoer": ["twist-off-honigglaser-500-g-12-stuck-inkl-deckel", "dib-einheitsglaser-500-g-12-stuck-inkl-deckel"],
    },
    # ------------------------------------------------------------------ Fütterungszubehör
    "futtertrog-8-l-fur-zander": {
        "vorteile": ["Acht Liter Fassungsvermögen", "Passend für Zanderbeuten", "Gitter für sicheren Einstieg", "Für flüssiges Bienenfutter"],
        "beutensysteme": ["Zander"],
        "claim": "Acht Liter Vorrat – ohne nasse Bienen.",
        "einleitung": "Der Futtertrog liegt auf dem Falz einer Leerzarge und fasst 8 Liter Flüssigfutter. Das integrierte Gitter unterstützt die Bienen beim sicheren Ein- und Ausstieg.",
        "kennzahlen": ["8 l | Fassungsvermögen", "47,5 × 37,5 cm | Grundfläche", "10 cm | Höhe", "Gitter | Aufstiegshilfe"],
        "anwendung": [
            "Leerzarge aufsetzen | Eine leere Zarge direkt auf das Volk setzen.",
            "Trog einlegen | Futtertrog auf den Falz der Leerzarge legen.",
            "Füllen & schließen | Flüssigfutter einfüllen und die Beute mit dem Deckel schließen.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Für die Auffütterung nach der letzten Honigernte.",
        "technische_daten": ["Beutensystem | Zander", "Fassungsvermögen | 8 l", "Maße | ca. 47,5 × 37,5 × 10 cm", "Material | Kunststoff", "Aufstieg | Integriertes Gitter", "Futterart | Flüssigfutter"],
        "lieferumfang": ["1 × Futtertrog 8 l (Leerzarge nicht enthalten)"],
        "faq": [
            "Brauche ich eine zusätzliche Zarge? | Ja, der Trog wird auf den Falz einer Leerzarge gelegt. Die Leerzarge ist nicht im Lieferumfang.",
            "Welches Futter eignet sich? | Flüssigfutter wie Zuckerlösung oder Futtersirup, zum Beispiel Apiinvert.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["apiinvert-bienenfutter-14-kg-eimer", "apiinvert-bienenfutter-16-kg-karton"],
    },
    "nicot-kunststoff-futterer-dadant-blatt-430-500-mm": {
        "vorteile": ["Für Dadant-Blatt-Beuten", "Maß 430 × 500 mm", "Robuster Kunststoff", "Für Flüssig- und Festfutter"],
        "beutensysteme": ["Dadant Blatt"],
        "claim": "Nicot-Qualität für Dadant Blatt.",
        "einleitung": "Der robuste Kunststoff-Fütterer von Nicot ist auf Dadant-Blatt-Beuten im Maß 430 × 500 mm abgestimmt. Ob Flüssig- oder Festfutter: Du versorgst deine Völker mit einem Handgriff.",
        "kennzahlen": ["430 × 500 mm | Fütterermaß", "Nicot | Hersteller", "Flüssig & fest | Futterarten", "Kunststoff | robust"],
        "anwendung": [
            "Aufsetzen | Fütterer auf die oberste Zarge deiner Dadant-Blatt-Beute setzen.",
            "Befüllen | Flüssigfutter oder Futterteig einbringen.",
            "Schließen | Beute mit dem Deckel verschließen und regelmäßig kontrollieren.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Hauptsächlich zur Auffütterung im Spätsommer.",
        "technische_daten": ["Beutensystem | Dadant Blatt", "Maß | 430 × 500 mm", "Material | Kunststoff", "Hersteller | Nicot", "Futterart | Flüssig- und Festfutter"],
        "lieferumfang": ["1 × Nicot Kunststoff-Fütterer 430 × 500 mm"],
        "faq": [
            "Kann ich auch Futterteig verwenden? | Ja, der Fütterer eignet sich für Flüssig- und Festfutter.",
            "Passt der Fütterer auf Zander? | Nein, er ist für Dadant Blatt (430 × 500 mm). Für Zander empfehlen wir die Nicot-Futterzarge.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["apiinvert-bienenfutter-14-kg-eimer", "apifonda-bienenfutterteig-15-kg-karton"],
    },
    "nicot-futterzarge-10-kg-zander-langstroth": {
        "vorteile": ["Zehn Kilogramm Futterkapazität", "Zwei getrennte Futterkammern", "Für Flüssigfutter und Futterteig", "Auch als Bienenflucht nutzbar"],
        "beutensysteme": ["Zander", "Liebig", "Langstroth", "Dadant"],
        "claim": "Zwei Kammern, zehn Kilo, eine Bienenflucht.",
        "einleitung": "Die Nicot-Futterzarge fasst in zwei getrennten Kammern je 5 kg Futter – Sirup, Zuckerlösung oder Teig. Über die Schieber regelst du jede Kammer einzeln und nutzt die Zarge bei Bedarf sogar als Bienenflucht.",
        "kennzahlen": ["2 × 5 kg | Futterkammern", "430 × 510 × 60 mm | Außenmaß", "4 | Beutensysteme", "Schieber | einzeln regelbar"],
        "anwendung": [
            "Aufsetzen | Futterzarge direkt auf die oberste Zarge setzen.",
            "Befüllen | Beide Kammern mit Flüssigfutter oder Futterteig befüllen.",
            "Regeln | Über die Schieber den Zugang je Kammer öffnen – oder als Bienenflucht einstellen.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Zur Auffütterung im Spätsommer – als Bienenflucht auch vor der Honigernte.",
        "technische_daten": ["Beutensysteme | Zander, Liebig, 10er Langstroth, 10er Dadant", "Außenmaß | 430 × 510 × 60 mm", "Kapazität | 2 Kammern à 5 kg", "Futterart | Flüssigfutter und Futterteig", "Zusatzfunktion | Bienenflucht über Schieber", "Hersteller | Nicot"],
        "lieferumfang": ["1 × Nicot Futterzarge 10 kg"],
        "faq": [
            "Wie funktioniert die Bienenflucht? | Über die Schieber lässt sich der Durchgang je Kammer so einstellen, dass die Bienen den darüberliegenden Bereich verlassen, aber nicht mehr zurückkehren.",
            "Wie reinige ich die Futterzarge? | Die Futterzarge lässt sich leicht reinigen und desinfizieren.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["apiinvert-bienenfutter-14-kg-eimer", "apifonda-bienenfutterteig-12-1-kg"],
    },
    "futtertasche-zander-477-220-mm": {
        "vorteile": ["Für Zander-Beuten", "Lebensmittelechter Kunststoff", "Drei getrennte Kammern", "Spülmaschinenfest und pflegeleicht"],
        "beutensysteme": ["Zander"],
        "claim": "Füttern wie ein Rähmchen – direkt im Brutraum.",
        "einleitung": "Die Futtertasche wird wie ein Rähmchen in die Zander-Zarge gehängt. Drei Kammern und geriffelte Innenwände als Aufstiegshilfe machen die Fütterung mit Flüssigfutter sauber und sicher – und danach geht sie einfach in die Spülmaschine.",
        "kennzahlen": ["477 × 220 mm | Taschenmaß", "3 | Kammern", "Lebensmittelecht | Kunststoff", "Spülmaschinenfest | pflegeleicht"],
        "anwendung": [
            "Platz schaffen | Eine Randwabe aus der Zarge nehmen.",
            "Einhängen | Futtertasche wie ein Rähmchen an den Rand des Wabensitzes hängen.",
            "Befüllen | Flüssigfutter einfüllen und bei Bedarf nachfüllen.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Ideal für die Auffütterung und für Ableger, die kleinere Portionen brauchen.",
        "technische_daten": ["Beutensystem | Zander", "Maß | 477 × 220 mm", "Kammern | 3", "Material | Lebensmittelechter Kunststoff", "Aufstiegshilfe | Geriffelte Innenwände", "Reinigung | Spülmaschinenfest"],
        "lieferumfang": ["1 × Futtertasche Zander 477 × 220 mm"],
        "faq": [
            "Ertrinken Bienen in der Tasche? | Die geriffelten Innenwände dienen als Aufstiegshilfe, damit die Bienen sicher wieder herausfinden.",
            "Kann ich die Tasche in die Spülmaschine geben? | Ja, sie ist spülmaschinenfest.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["apiinvert-bienenfutter-14-kg-eimer", "apiinvert-bienenfutter-16-kg-karton"],
    },
    "futtertasche-dadant-446-285-mm": {
        "vorteile": ["Für Dadant-Beuten", "Lebensmittelechter Kunststoff", "Drei getrennte Kammern", "Spülmaschinenfest und pflegeleicht"],
        "beutensysteme": ["Dadant"],
        "claim": "Die Futtertasche für das große Dadant-Maß.",
        "einleitung": "Für die hohen Dadant-Rähmchen gemacht: Die Futtertasche hängt wie eine Wabe in der Zarge und bietet in drei Kammern Platz für Flüssigfutter. Geriffelte Wände helfen den Bienen beim Aufstieg.",
        "kennzahlen": ["446 × 285 mm | Taschenmaß", "3 | Kammern", "Lebensmittelecht | Kunststoff", "Spülmaschinenfest | pflegeleicht"],
        "anwendung": [
            "Platz schaffen | Eine Randwabe aus der Dadant-Zarge nehmen.",
            "Einhängen | Futtertasche wie ein Rähmchen einhängen.",
            "Befüllen | Flüssigfutter einfüllen und bei Bedarf nachfüllen.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Ideal für die Auffütterung im Spätsommer.",
        "technische_daten": ["Beutensystem | Dadant", "Maß | 446 × 285 mm", "Kammern | 3", "Material | Lebensmittelechter Kunststoff", "Aufstiegshilfe | Geriffelte Innenwände", "Reinigung | Spülmaschinenfest"],
        "lieferumfang": ["1 × Futtertasche Dadant 446 × 285 mm"],
        "faq": [
            "Ertrinken Bienen in der Tasche? | Die geriffelten Innenwände dienen als Aufstiegshilfe, damit die Bienen sicher wieder herausfinden.",
            "Kann ich die Tasche in die Spülmaschine geben? | Ja, sie ist spülmaschinenfest.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["apiinvert-bienenfutter-14-kg-eimer", "dadant-brutraum-mittelwaende-420-260-mm-1-kg"],
    },
    "futtertasche-deutsch-normal-393-220-mm": {
        "vorteile": ["Für Deutsch-Normalmaß-Beuten", "Lebensmittelechter Kunststoff", "Drei getrennte Kammern", "Spülmaschinenfest und pflegeleicht"],
        "beutensysteme": ["Deutsch Normal"],
        "claim": "Passgenau füttern im Deutsch Normalmaß.",
        "einleitung": "Die Futtertasche im Format 393 × 220 mm hängt wie ein DNM-Rähmchen in der Zarge. Drei Kammern und geriffelte Innenwände als Aufstiegshilfe – und nach der Saison ab in die Spülmaschine.",
        "kennzahlen": ["393 × 220 mm | Taschenmaß", "3 | Kammern", "Lebensmittelecht | Kunststoff", "Spülmaschinenfest | pflegeleicht"],
        "anwendung": [
            "Platz schaffen | Eine Randwabe aus der Zarge nehmen.",
            "Einhängen | Futtertasche wie ein DNM-Rähmchen einhängen.",
            "Befüllen | Flüssigfutter einfüllen und bei Bedarf nachfüllen.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Ideal für die Auffütterung und für Ableger.",
        "technische_daten": ["Beutensystem | Deutsch Normalmaß", "Maß | 393 × 220 mm", "Kammern | 3", "Material | Lebensmittelechter Kunststoff", "Aufstiegshilfe | Geriffelte Innenwände", "Reinigung | Spülmaschinenfest"],
        "lieferumfang": ["1 × Futtertasche Deutsch Normal 393 × 220 mm"],
        "faq": [
            "Ertrinken Bienen in der Tasche? | Die geriffelten Innenwände dienen als Aufstiegshilfe, damit die Bienen sicher wieder herausfinden.",
            "Kann ich die Tasche in die Spülmaschine geben? | Ja, sie ist spülmaschinenfest.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["apiinvert-bienenfutter-14-kg-eimer", "dnm-mittelwaende-350-200-mm-1-kg"],
    },
    # ------------------------------------------------------------------ Bienenfutter: Sirup
    "apiinvert-bienenfutter-14-kg-eimer": {
        "vorteile": ["14 kg im Eimer", "Sofort gebrauchsfertiger Sirup", "Geringe Kristallisationsneigung", "Für saisonale Auffütterung"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Auffüttern ohne Anrühren – 14 kg im handlichen Eimer.",
        "einleitung": "Apiinvert ist ein gebrauchsfertiger Futtersirup aus Saccharose, Glucose und Fructose. Er kristallisiert kaum aus und lässt sich direkt aus dem Eimer in Futtertasche, Trog oder Futterzarge füllen.",
        "kennzahlen": ["14 kg | Eimer", "3 Zuckerarten | Saccharose, Glucose, Fructose", "Gebrauchsfertig | ohne Anrühren", "Gering | Kristallisationsneigung"],
        "anwendung": [
            "Fütterer vorbereiten | Futtertasche, Futtertrog oder Futterzarge an der Beute bereitstellen.",
            "Einfüllen | Apiinvert direkt aus dem Eimer einfüllen – Verdünnen ist nicht nötig.",
            "Nachfüllen | Futteraufnahme beobachten und portionsweise nachfüllen.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Zur Auffütterung nach der letzten Honigernte.",
        "technische_daten": ["Produkt | Apiinvert Futtersirup", "Gebinde | 14-kg-Eimer", "Zusammensetzung | Saccharose, Glucose, Fructose", "Zubereitung | Gebrauchsfertig", "Hersteller | Südzucker"],
        "lieferumfang": ["1 × Apiinvert Futtersirup, 14-kg-Eimer"],
        "faq": [
            "Muss ich Apiinvert verdünnen? | Nein, der Sirup ist gebrauchsfertig.",
            "Wie wird der Sirup gefüttert? | Über Futtertasche, Futtertrog oder Futterzarge.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["futtertasche-zander-477-220-mm", "futtertrog-8-l-fur-zander", "nicot-futterzarge-10-kg-zander-langstroth"],
    },
    "apiinvert-bienenfutter-16-kg-karton": {
        "vorteile": ["16 kg im Karton", "Sofort gebrauchsfertiger Sirup", "Geringe Kristallisationsneigung", "Für Winter- und Notfütterung"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "16 kg Wintervorrat für deine Völker.",
        "einleitung": "Der gebrauchsfertige Apiinvert-Sirup im 16-kg-Karton ist die solide Basis für die Einwinterung – und eignet sich auch für die Notfütterung. Die Zuckermischung aus Saccharose, Glucose und Fructose kristallisiert kaum aus.",
        "kennzahlen": ["16 kg | Karton", "3 Zuckerarten | Saccharose, Glucose, Fructose", "Gebrauchsfertig | ohne Anrühren", "Winter & Not | Einsatz"],
        "anwendung": [
            "Fütterer vorbereiten | Futtertasche, Futtertrog oder Futterzarge bereitstellen.",
            "Einfüllen | Sirup direkt aus dem Karton einfüllen.",
            "Kontrollieren | Futteraufnahme beobachten und nachfüllen, bis der Wintervorrat steht.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Zur Einwinterung im Spätsommer – bei Futtermangel auch als Notfütterung.",
        "technische_daten": ["Produkt | Apiinvert Futtersirup", "Gebinde | 16-kg-Karton", "Zusammensetzung | Saccharose, Glucose, Fructose", "Zubereitung | Gebrauchsfertig", "Hersteller | Südzucker"],
        "lieferumfang": ["1 × Apiinvert Futtersirup, 16-kg-Karton"],
        "faq": [
            "Eignet sich der Sirup auch zur Notfütterung? | Ja, Apiinvert im 16-kg-Karton ist für Winter- und Notfütterung geeignet.",
            "Muss ich Apiinvert verdünnen? | Nein, der Sirup ist gebrauchsfertig.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["nicot-futterzarge-10-kg-zander-langstroth", "futtertrog-8-l-fur-zander", "futtertasche-zander-477-220-mm"],
    },
    "apiinvert-bienenfutter-28-kg-karton": {
        "vorteile": ["28 kg im Großkarton", "Sofort gebrauchsfertiger Sirup", "Für saisonale Auffütterung", "Versorgt ganze Bienenvölker"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Das Großgebinde für den ganzen Bienenstand.",
        "einleitung": "Wer mehrere Völker einwintert, spart mit dem 28-kg-Karton Wege und Verpackung. Apiinvert ist gebrauchsfertig und wird ohne Anrühren direkt in die Fütterer gefüllt.",
        "kennzahlen": ["28 kg | Großkarton", "Gebrauchsfertig | ohne Anrühren", "Mehrere | Völker versorgen", "Apiinvert | Futtersirup"],
        "anwendung": [
            "Planen | Futterbedarf deiner Völker abschätzen und Fütterer bereitstellen.",
            "Einfüllen | Sirup direkt in Futtertasche, Trog oder Futterzarge füllen.",
            "Verteilen | Portionsweise auf alle Völker verteilen und nachfüllen.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Zur Auffütterung mehrerer Völker nach der letzten Honigernte.",
        "technische_daten": ["Produkt | Apiinvert Futtersirup", "Gebinde | 28-kg-Karton", "Zubereitung | Gebrauchsfertig", "Hersteller | Südzucker"],
        "lieferumfang": ["1 × Apiinvert Futtersirup, 28-kg-Karton"],
        "faq": [
            "Für wen lohnt sich der 28-kg-Karton? | Für Imkereien mit mehreren Völkern – du kaufst in einem Gebinde statt in vielen kleinen.",
            "Muss ich Apiinvert verdünnen? | Nein, der Sirup ist gebrauchsfertig.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["nicot-futterzarge-10-kg-zander-langstroth", "futtertrog-8-l-fur-zander"],
    },
    "apiinvert-bienenfutter-5-2-5-kg": {
        "vorteile": ["Fünf Beutel à 2,5 kg", "Direkt auf Rähmchen auflegen", "Kein Umfüllen erforderlich", "Einfach portionsweise füttern"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Anstechen, auflegen, fertig.",
        "einleitung": "Fünf Beutel à 2,5 kg Apiinvert, die ohne Fütterer auskommen: Löcher hineinstechen, Beutel auf die Rähmchen legen – die Bienen nehmen den Sirup direkt aus dem Beutel. Kein Umfüllen, kein Kleckern.",
        "kennzahlen": ["5 × 2,5 kg | Beutel", "3–5 | Löcher pro Beutel", "ca. 1 mm | Lochgröße", "0 | Fütterer nötig"],
        "anwendung": [
            "Anstechen | 3 bis 5 Löcher mit ca. 1 mm Durchmesser in einen 2,5-kg-Beutel stechen.",
            "Auflegen | Beutel mit den Löchern nach unten direkt auf die Rähmchen legen.",
            "Abdecken | Leerzarge aufsetzen und die Beute mit dem Deckel schließen.",
        ],
        "einsatzmonate": ["Jul", "Aug", "Sep"],
        "einsatz_hinweis": "Ideal für die Auffütterung und für kleinere Völker oder Ableger.",
        "technische_daten": ["Produkt | Apiinvert Futtersirup", "Gebinde | 5 Beutel à 2,5 kg im Karton", "Anwendung | Beutel anstechen und auflegen", "Hersteller | Südzucker"],
        "lieferumfang": ["5 × Apiinvert-Beutel à 2,5 kg im Karton"],
        "faq": [
            "Wie viele Löcher steche ich in den Beutel? | 3 bis 5 Löcher mit etwa 1 mm Durchmesser.",
            "Brauche ich einen Fütterer? | Nein, der Beutel wird direkt auf die Rähmchen gelegt. Du brauchst nur Platz darüber, zum Beispiel eine Leerzarge.",
            _FUTTER_FAQ_WANN,
        ],
        "zubehoer": ["apifonda-bienenfutterteig-12-1-kg", "apiinvert-bienenfutter-16-kg-karton"],
    },
    # ------------------------------------------------------------------ Bienenfutter: Teig
    "apifonda-bienenfutterteig-12-1-kg": {
        "vorteile": ["12 einzeln portionierte Kilogramm", "Sofort gebrauchsfertig", "Hohe Akzeptanz bei Bienen", "Für Winter- und Notfütterung"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Ein Kilo Energie – genau dort, wo dein Volk es braucht.",
        "einleitung": "Apifonda besteht aus feinen Saccharose-Kristallen in einer speziellen Zuckerlösung und wird von Bienen besonders gut angenommen. Die zwölf 1-kg-Portionen legst du sauber und ohne Anrühren auf – ideal für Notfütterung, Frühjahr und Ableger.",
        "kennzahlen": ["12 × 1 kg | Portionen", "Sofort | gebrauchsfertig", "Hoch | Akzeptanz", "Lange | lagerfähig"],
        "anwendung": [
            "Öffnen | Folie einer 1-kg-Portion an der Unterseite kreuzweise einschneiden.",
            "Auflegen | Portion mit der Öffnung nach unten direkt über dem Bienensitz auf die Rähmchen legen.",
            "Kontrollieren | Nach einigen Tagen nachsehen und bei Bedarf eine neue Portion nachlegen.",
        ],
        "einsatzmonate": ["Feb", "Mär", "Apr", "Mai", "Jun", "Jul"],
        "einsatz_hinweis": "Im zeitigen Frühjahr zur Not- und Übergangsfütterung, im Sommer für Ableger – und bei Futtermangel im Winter.",
        "technische_daten": ["Produkt | Apifonda Futterteig", "Gebinde | 12 × 1 kg", "Basis | Saccharose-Kristalle in Zuckerlösung", "Zubereitung | Sofort gebrauchsfertig", "Hersteller | Südzucker"],
        "lieferumfang": ["12 × Apifonda Futterteig à 1 kg"],
        "faq": [
            "Wann setze ich Futterteig statt Sirup ein? | Futterteig eignet sich besonders für Notfütterung, das zeitige Frühjahr und Ableger, weil die Bienen ihn direkt und nach und nach aufnehmen können.",
            "Muss ich Apifonda auflösen? | Nein, der Teig wird direkt aufgelegt und von den Bienen ohne Auflösen oder Verdünnen aufgenommen.",
            "Wie lagere ich die Portionen? | Kühl, trocken und verschlossen. Apifonda ist lange lagerfähig.",
        ],
        "zubehoer": ["nicot-futterzarge-10-kg-zander-langstroth", "apiinvert-bienenfutter-16-kg-karton"],
    },
    "apifonda-bienenfutterteig-5-2-5-kg": {
        "vorteile": ["Fünf praktische Einzelportionen", "Sofort gebrauchsfertig", "Hohe Akzeptanz bei Bienen", "Für Winter- und Notfütterung"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "Großzügige Portionen für starke Völker.",
        "einleitung": "Fünf Portionen à 2,5 kg Apifonda: Mehr Futter pro Handgriff für starke Völker, ohne Anrühren und sauber aufzulegen. Die feine Kristallstruktur sorgt dafür, dass die Bienen den Teig gut annehmen.",
        "kennzahlen": ["5 × 2,5 kg | Portionen", "Sofort | gebrauchsfertig", "Hoch | Akzeptanz", "Lange | lagerfähig"],
        "anwendung": [
            "Öffnen | Folie einer 2,5-kg-Portion an der Unterseite einschneiden.",
            "Auflegen | Portion mit der Öffnung nach unten über dem Bienensitz auf die Rähmchen legen.",
            "Raum schaffen | Leerzarge oder Futterzarge aufsetzen und die Beute schließen.",
        ],
        "einsatzmonate": ["Feb", "Mär", "Apr", "Mai", "Jun", "Jul"],
        "einsatz_hinweis": "Für Not- und Übergangsfütterung im Frühjahr und zur Versorgung im Sommer.",
        "technische_daten": ["Produkt | Apifonda Futterteig", "Gebinde | 5 × 2,5 kg", "Basis | Saccharose-Kristalle in Zuckerlösung", "Zubereitung | Sofort gebrauchsfertig", "Hersteller | Südzucker"],
        "lieferumfang": ["5 × Apifonda Futterteig à 2,5 kg"],
        "faq": [
            "1 kg oder 2,5 kg – was passt besser? | 2,5-kg-Portionen eignen sich für starke Völker, 1-kg-Portionen für kleinere Völker, Ableger und feinere Dosierung.",
            "Muss ich Apifonda auflösen? | Nein, der Teig wird direkt aufgelegt.",
            "Wie lagere ich die Portionen? | Kühl, trocken und verschlossen. Apifonda ist lange lagerfähig.",
        ],
        "zubehoer": ["apifonda-bienenfutterteig-12-1-kg", "nicot-futterzarge-10-kg-zander-langstroth"],
    },
    "apifonda-bienenfutterteig-15-kg-karton": {
        "vorteile": ["15 kg im Großgebinde", "Ohne Anrühren einsetzbar", "Für Ableger- und Notfütterung", "Saubere, einfache Anwendung"],
        "beutensysteme": ["Systemunabhängig"],
        "claim": "15 kg Futterteig für die ganze Saison.",
        "einleitung": "Der 15-kg-Karton Apifonda ist das wirtschaftliche Großgebinde für Imker mit mehreren Völkern oder vielen Ablegern. Der Teig wird ohne Anrühren eingesetzt – du portionierst einfach so viel, wie du brauchst.",
        "kennzahlen": ["15 kg | Großgebinde", "Sofort | gebrauchsfertig", "Ableger & Not | Einsatz", "Frei | portionierbar"],
        "anwendung": [
            "Portionieren | Benötigte Menge abstechen und in Folie oder eine Futterschale geben.",
            "Auflegen | Teig direkt über dem Bienensitz auf die Rähmchen oder in den Fütterer legen.",
            "Lagern | Restmenge gut verschlossen, kühl und trocken aufbewahren.",
        ],
        "einsatzmonate": ["Feb", "Mär", "Apr", "Mai", "Jun", "Jul"],
        "einsatz_hinweis": "Für Ableger im Sommer und als Notfütterung im zeitigen Frühjahr.",
        "technische_daten": ["Produkt | Apifonda Futterteig", "Gebinde | 15-kg-Karton", "Zubereitung | Sofort gebrauchsfertig", "Hersteller | Südzucker"],
        "lieferumfang": ["1 × Apifonda Futterteig, 15-kg-Karton"],
        "faq": [
            "Kann ich den Teig portionieren? | Ja, du entnimmst einfach die benötigte Menge und verschließt den Rest wieder gut.",
            "Eignet sich der Teig für Ableger? | Ja, Apifonda ist für die Ableger- und Notfütterung geeignet.",
            "Wie lagere ich den Karton? | Kühl, trocken und gut verschlossen.",
        ],
        "zubehoer": ["nicot-kunststoff-futterer-dadant-blatt-430-500-mm", "nicot-futterzarge-10-kg-zander-langstroth"],
    },
}

# Archivierte Produkte: nur die bisherigen Buy-Box-Vorteile übernehmen (vorher fest im Code).
ARCHIVED_VORTEILE = {
    "absperrgitter-zander-liebig-477-375-mm": ["Passend für Zander und Liebig", "Maß 477 × 375 mm", "Hält die Königin im Brutraum", "Klare Trennung zum Honigraum"],
    "beutenstaender-verzinkt-flexibel-einstellbar": ["Feuerverzinkt und wetterfest", "Für bis zu vier Beuten", "Höhe von 12–40 cm", "Auch für leichte Hanglagen"],
    "edelstahl-smoker-leder-blasebalg": ["Robuste Edelstahlausführung", "Blasebalg aus Leder", "Innenliegende Lochplatte", "Beruhigt Bienen am Stock"],
    "imkerhandschuhe-leder-groesse-l": ["Weiches Naturleder", "Atmungsaktiver Stoffeinsatz", "Passform in Größe L", "Ein Paar im Lieferumfang"],
    "zander-raehmchen-mit-mittelwand-10-stueck": ["Zehn fertige Rähmchen", "Mittelwände bereits eingebaut", "Mit Hoffmann-Seitenteilen", "Pestizidfreies Bienenwachs"],
}
